color 0A
echo off
cls
:start
echo "<!Doctype HTML>"
echo "<html lang="fr" class="is-nav-up">"
echo "<div>"
echo "    <head>"
echo "        <meta charset="utf-8"/>"
echo "        <link rel="stylesheet" type="text/css" href="css/sommaire/sommaire.css">"
echo "        <link href="http://www.gif-maniac.com/gifs/54/53541.gif" rel="shortcut icon">"
echo "        <title>CCL  (conclusion)</title>"
echo "        
echo "    </head>"
echo "    <body>"
echo "        <p id="top"></p>"
echo "        <header>"
echo "            <div style="background-color:  orange">"
echo "                <p><h1><B><I><center><Sommaire><strong>Ceci n'est pas un CCL</strong></Sommaire></center></I></B></h1></p>"
echo "                <p><center><h1><strong>Ceci est une conclusion</strong></h1></center></p>"
echo "                <div class="lpb">"
echo "                    <div id="lpt" style="width: 90%;">"
echo "                    </div>"
echo "                </div>"
echo "            </div>"
echo "        </header>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "         <nav>"
echo "            <ul>"
echo "                <li><cennter><a href="sommaire.html#top"><img src="img\check.png" ></img>Sommaire</a></cennter></li>"
echo "                <li><cennter><a href="présentation.html#QcqlBD"><img src="img\check.png" ></img>Qu’est ce que le Big Data?</a></cennter></li>"
echo "                    <li><cennter><a href="présentation.html#aqsti"><img src="img\check.png"></img>À quoi sert-t-il?</a></cennter></li>"
echo "                    <li><cennter><a href="présentation.html#Peisp"><img src="img\check.png" ></img>Pourquoi est il si populaire?</a></cennter></li>"
echo "                    <li><cennter><a href="présentation.html#QsledBD"><img src="img\check.png" ></img>Quels sont les enjeux du Big Data</a></cennter></li>"
echo "                    <li><cennter><a href="présentation.html#LBDgtidm"><img src="img\check.png" ></img>Le Big Data génère-t-il des métiers?</a></cennter></li>"
echo "                <li><cennter><a href="CCL.html#conclusion"><img src="img\check.png" ></img>conclusion</a></cennter></li>"
echo "                <li><cennter><a href="Sources.html"><img src="img\check.png" ></img>Sources</a></cennter></li>"
echo "             </ul>"
echo "        </nav>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <p><somaire><h1 id="conclusion">conclusion</h1></somaire></p>"
echo "        <p><size><B>Pour conclure...</B></size></p>"
echo "        <p>Le Big Data est né d’une réponse à un problème de temps de traitement des données, les massives quantités de données sont compressées.</p>"
echo "        <p>Ces données sont mises en relation et des calculs sont effectués grâce aux ordinateurs, ces données sont traités par des logiciels et des programmes.</p>"
echo "        <p>Les données collectées dans le cadre d’une étude Big Data peuvent avoir des origines et des formes très différentes, elles sont ensuite traités à travers des algorithmes et des structures adaptés dans le but de produire une information.</p>"
echo "        <p>Les systèmes de recommandation sont des algorithmes qui tirent profit du Big Data, l’information produite étant la recommandation d’un produit à l’utilisateur.</p>"
echo "        <p>On pourrait se demander si cette collecte massive de données peut nuire à notre vie privée et si la recommandation nous cache d’une partie de la diversité du web.</p>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <br>"
echo "        <footer style="background-image: url(https://www.tissus-et-tendance.fr/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/e/pe0410-bleu-royal-bache-performance-tarp-tissus-et-tendance.jpg)" item-heigt="10" item-width="10">"
echo "            <p><h3>Pages</h3></p>"
echo "            <br>"
echo "            <section>"
echo "                <p><center><a href="présentation.html"><button id="before" style="background-color: yellowgreen" item-height="100" item-width="200"><img src="img\arrow-left@2x.png" ></img>précedent</a></button><a href="Sources.html"><button id="after" style="background-color: yellowgreen" item-height="100" item-width="200">prochain<img src="img\arrow-right@2x.png"></img></a></button></center></p>"
echo "            </section>"
echo "            <br>"
echo "            <br>"
echo "            <br>"
echo "            <br>"
echo "        </footer>"
echo "    </body>"
echo "</div>"
echo "</html>"
pause
cmd/c "C:\Users\ELEVE\Dropbox\ICN\CCL.html"
pause
pause
pause